### ISSUE TITLE
Integrate this to infolis-datasets?

### ISSUE THREAD

**Issue by kba** [infolis/corpus-creation#1]
Put this in https://github.com/infolis/infolis-datasets/tree/master/datasets/ssoar of https://github.com/infolis/infolis-datasets ? Then it would be right where the data is.

**Comment by bolandka** [comment]
Good point. However, the tools here are not (only) to be used for creating subsets of ssoar. They can be used to create subsets of econStor documents (querying the indices created by parsing the metadata) or to draw a random sample from any corpus. Likewise, the stpCommandCreator tool can be used to prepare queries to extract specific documents from any corpus. I'll probably extend the econMetaHandler to a more general parser that may also handle ssoar and other metadata (the names are pretty bad I have to admit and the code quite simplistic right now, I'll make it more customizable as soon as the need be). But it's a good point to put them somewhat closer to the datasets. How about moving the contents of this repo to https://github.com/infolis/infolis-datasets, make the tools read their parameters from json-files and put those files in the corresponding dataset folders? (e.g. parameter files for creating a subset of ssoar to https://github.com/infolis/infolis-datasets/tree/master/datasets/ssoar)

**Comment by kba** [comment]
Yes, that is what I meant.

**Comment by bolandka** [comment]
Done.
